---
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: multiclusterengine
  labels:
    app.kubernetes.io/instance: hub-operators-config
    installer.name: multiclusterhub
    installer.namespace: open-cluster-management
    multiclusterhubs.operator.open-cluster-management.io/managed-by: "true"
spec:
  availabilityConfig: High
  targetNamespace: multicluster-engine
  overrides:
    components:
    - configOverrides: {}
      enabled: true
      name: image-based-install-operator
    - configOverrides: {}
      enabled: false
      name: hypershift
    - configOverrides: {}
      enabled: false
      name: hypershift-local-hosting
    - configOverrides: {}
      enabled: true
      name: assisted-service
    - configOverrides: {}
      enabled: true
      name: cluster-lifecycle
    - configOverrides: {}
      enabled: true
      name: cluster-manager
    - configOverrides: {}
      enabled: true
      name: discovery
    - configOverrides: {}
      enabled: true
      name: hive
    - configOverrides: {}
      enabled: true
      name: server-foundation
    - configOverrides: {}
      enabled: true
      name: cluster-proxy-addon
    - configOverrides: {}
      enabled: true
      name: local-cluster
    - configOverrides: {}
      enabled: true
      name: managedserviceaccount
    - configOverrides: {}
      enabled: false
      name: cluster-api
    - configOverrides: {}
      enabled: false
      name: cluster-api-provider-aws
    - configOverrides: {}
      enabled: true
      name: console-mce

