---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: local-block
  namespace: openshift-local-storage
spec:
  logLevel: Normal
  managementState: Managed
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - hub-ctlplane-0.hub.5g-deployment.lab
        - hub-ctlplane-1.hub.5g-deployment.lab
        - hub-ctlplane-2.hub.5g-deployment.lab
  storageClassDevices:
  - devicePaths:
    - /dev/disk/by-path/pci-0000:09:00.0
    storageClassName: localblock
    volumeMode: Block

