apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00_namespace.yaml
  - 01_pvc.yaml
  - 02_configmap.yaml
  - 03_deployment.yaml
  - 04_service.yaml
  - 05_route_node0.yaml
  - 05_route_node1.yaml
  - 05_route_node2.yaml

# Uncomment if using LoadBalancer instead of NodePort
# - 06_service_loadbalancer.yaml

# Remove 04_service.yaml from resources if using LoadBalancer
# resources:
#   - 00_namespace.yaml
#   - 01_pvc.yaml
#   - 02_configmap.yaml
#   - 03_deployment.yaml
#   - 06_service_loadbalancer.yaml
#   - 05_route_node0.yaml
#   - 05_route_node1.yaml
#   - 05_route_node2.yaml
